### ISSUE TITLE
Asignación de tareas con clase Fraction

### ISSUE THREAD

**Issue by fer2d2** [Jorge91/SpaiEcp2JorgeRabanos#10]
Hola Jorge,

Aunque creo que ya lo sabes, sería necesario que asignes a los miembros del equipo la tarea que tenemos que realizar cada uno con la clase Fraction (Mejoras de la 7 a la 9).

¿O quizá estabas esperando a que todos terminemos nuestras partes del hito1?

¡Gracias!

**Comment by Jorge91** [comment]
Jajaj sí, estoy esperando a que se acabe el hito.
Pero gracias de todos modos!
