### ISSUE TITLE
Subida de ramas Feature

### ISSUE THREAD

**Issue by fer2d2** [Jorge91/SpaiEcp2JorgeRabanos#11]
Hola Jorge,

He mandado un correo a Jesús Bernal y me ha comentado que subamos nuestras ramas de desarrollo:

Cito:

> Las ramas featuresXX locales, es mejor borrarlas, ya que no tienen más utilidad, dejaremos las ramas origin/featuresXX remotas, con la utilidad de que yo pueda rastrear lo que ha ocurrido.

¿Cómo lo ves? ¿Las subimos?

**Comment by Jorge91** [comment]
Vale, me parece bien. Porque ahora mismo parece que sólo ha existido la rama develop.

**Comment by fer2d2** [comment]
¡Ya he subido las mías!

Haré lo propio cuando comencemos el _hito 2_.

¡Un saludo!
